### ISSUE TITLE
Issue after updating vue-formulate to 2.5.0

### ISSUE THREAD

**Issue by IRunac** [gahabeen/vue-formulate-extended#14]
I'm getting this error after updating vue-formulate to newest version:
`Error in callback for watcher "formulateValue": "TypeError: o.shallowEqualObjects is not a function"`

Seems like you are using a method from vue-formulate utils.js that got renamed in the latest version. 
From `shallowEqualObjects` to `equals`.

**Comment by miguelcarrillo** [comment]
Same problem, still not solved!

**Comment by CavalcanteLeo** [comment]
Same here

the function `shallowEqualObjects ` was renamed to `equals`
https://github.com/wearebraid/vue-formulate/blob/master/src/libs/utils.js#L22

**Comment by minasvisual** [comment]
Same problem, same disabled features, and hook models not working anymore without plugin

**Comment by CavalcanteLeo** [comment]
I have fixed this issue and submitted a PR, but seems this is an abandoned project  
https://github.com/gahabeen/vue-formulate-extended/pull/18

**Comment by minasvisual** [comment]
Send an email to him, lets try continue the project dude!

**Comment by gahabeen** [comment]
Hey, sorry but this project was indeed put on pause. I'll have a look tomorrow and keep you guys posted!
